[package]
name = "MathCatForPython"
version = "0.1.3"
authors = ["Neil Soiffer <soiffer@alum.mit.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [dependencies]

[lib]
name = "libmathcat_py"
crate-type = ["cdylib"]

[dependencies]
mathcat = "0.1.13"

[dependencies.pyo3]
version = "0.15.1"
features = ["extension-module", "abi3"]

[build-dependencies]
mathcat = "0.1.13"
zip = "0.5.8"

[profile.release]
lto = true
# opt-level = "z"  # Optimize for size.
