[package]
name = "MathCAT"
version = "0.1.0"
authors = ["Neil Soiffer <soiffer@alum.mit.edu>"]
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sxd-document = "0.3.2"
sxd-xpath = "0.4.2"
#sxd-xpath = {path = "../sxd-xpath-0.4.2"}
yaml-rust = "0.4"
lazy_static = "1.4.0"
strum = "0.20"
strum_macros = "0.20"
structopt = "*"
error-chain = "*"
regex = "1.5"
dirs = "3.0"
bitflags = "1.2.1"
phf = { version = "0.8.0", features = ["macros"] }
internment = "0.5.4"

[build-dependencies]
bitflags = "1.2.1"
phf = { version = "0.8.0", features = ["macros"] }

# slog = "2.7"
# sloggers = "1.0.1"
# slog-term = "2.8"
# slog-async = "2.6"
# slog-envlogger = "0.4.2"
# slog-stdlog = "4.1.0"
# log = "0.4.14"

# intercom = "0.3.0"
# com = "0.4.0"
# windows = "0.3.1"
# bindings = { package = "windows_bindings", path = "bindings" }

# [build-dependencies]
# windows = "0.3.1"

[[bin]]
name = "mathcat"
path = "src/main.rs"

[lib]
name = "libmathcat"
crate-type = ["rlib", "cdylib"]

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module", "abi3"]

# 32 bit target stable-i686-pc-windows-msvc
# if changing to building 32 bit python version, change .cargo/config.toml
#  along with changing env variable PYO3_PYTHON
