name: automatic-release

on:
  push:
    branches:
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * 6'

jobs:
  l10n:
    name: l10n
    continue-on-error: true
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Push l10n updates
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git remote add l10n https://github.com/nvdaaddons/MathCAT
        git fetch l10n
        git reset l10n/stable addon/doc addon/locale
        git commit -m "Update translations"
        git pull
        git push
  
  rust:  
    name: build pyd file
    needs: l10n
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        architecture: 'x86'
    - name: Set up Rust 
      run:  cargo build --target i686-pc-windows-msvc --release
    - name: Copy MathCAT.pyd file and fix wx file
      run: |
        cp target/i686-pc-windows-msvc/release/libmathcat_py.dll addon/globalPlugins/MathCAT/libmathcat.pyd
        sed 's/^import wx\.xrc/# import wx.xrc/' --in-place "addon/globalPlugins/MathCAT/MathCATgui.py"
    
  scons:
    name: Build with scons
    continue-on-error: false
    needs: rust
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        pip install scons markdown
        sudo apt update
        sudo apt install gettext
    - name: Run scons
      run: scons  

  pre-release:  
    name: Pre Release
    needs: scons
    runs-on: windows-latest
    steps:
    - name: Automatic release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: latest
        prerelease: true
        title: Development Build
        files: |
          *.nvda-addon
