name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  lint:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: code
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies (flake8)
      run: pip install -r requirements.txt
    - name: Lint
      run: flake8 code/addon --max-line-length=130 --extend-exclude=addon/globalPlugins/MathCAT/yaml/*